select * from system.ingresstest /* definite */ ;
select id from system.ingresstest /* definite */ ;
select id from system.ingresstest where id = 0 /* definite */ ;
select id from system.ingresstest where id = 1 /* definite */ ;
select time from system.ingresstest where id = 0 /* definite */ ;
select id from system.ingresstest where id <= 0 /* definite */ ;
select id from system.ingresstest where id >= 0 /* definite */ ;
select id from system.ingresstest where id > 0 /* definite */ ;
select id from system.ingresstest where id < 0 /* definite */ ;
select id from system.ingresstest where id <> 0 /* definite */ ;
select id from system.ingresstest where not id = 0 /* definite */ ;
select id, time from system.ingresstest /* definite */ ;
select id from system.ingresstest where id > 1 and id < 4 /* definite */ ;
select id from system.ingresstest where id = 2 or id = 5 /* definite */ ;
select id from system.ingresstest where id < 2 or id > 5 /* definite */ ;
select id from system.ingresstest where id between 1 and 4 /* definite */ ;
select id from system.ingresstest where id in (3, 6) /* definite */ ;
select id + 1 from system.ingresstest /* definite */ ;
select clusterleft + clusterright from system.ingresstest /* definite */ ;
select id + 1 as newid from system.ingresstest /* definite */ ;
select 2*id as doubleid from system.ingresstest /* definite */ ;
select power(2, id) from system.ingresstest /* definite */ ;
select count(*) from system.ingresstest /* definite */ ;
select count(id) from system.ingresstest /* definite */ ;
select val0, count(*) from system.ingresstest group by val0 /* definite */ ;
select max(val0) from system.ingresstest /* definite */ ;
select val0, max(id) from system.ingresstest group by val0 /* definite */ ;
select min(val0) from system.ingresstest /* definite */ ;
select val0, min(id) from system.ingresstest group by val0 /* definite */ ;
select val0, val1, count(*) as cnt from system.ingresstest group by val0, val1 /* definite */ ;
select max(val0), sum(val0) from system.ingresstest /* definite */ ;
select val1, val2, count(*) as cnt from system.ingresstest group by val1, val2 /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by s /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by s asc /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by val0, val1 /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by val0 desc, val1 /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by val0, val1 desc /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by val0 asc, val1 desc /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by val0 asc, val1 desc limit 10 /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by val0 asc, val1 desc offset 10 /* definite */ ;
select val0, val1, max(val2) as m, sum(val2) as s from system.ingresstest group by val0, val1 order by val0 asc, val1 desc limit 10 offset 10 /* definite */ ;
select * from system.ingresstest order by clusterextra, clusterright /* definite */ ;
select * from system.ingresstest order by clusterextra, clusterright limit 10 /* definite */ ;
select * from system.ingresstest limit 10 /* definite */ ;
select * from system.ingresstest order by clusterextra, clusterright offset 10 /* definite */ ;
select * from system.ingresstest offset 10 /* definite */ ;
select * from system.ingresstest order by clusterextra, clusterright limit 10 offset 10 /* definite */ ;
select * from system.ingresstest limit 10 offset 10 /* definite */ ;
select sum(val0)+1 from system.ingresstest /* definite */ ;
select (min(val0) + max(val0)) / 2 from system.ingresstest /* definite */ ;
select val0, count(val1)+1 from system.ingresstest group by val0 having count(val1) > 2 /* definite */ ;
select val0, count(val1)+1 from system.ingresstest group by val0 having count(val1) > 2 order by val0 limit 5 /* definite */ ;
select val0 from system.ingresstest group by val0 having count(val1) > 2 /* definite */ ;
select val0 from system.ingresstest group by val0 having count(val1)+1 > 2 /* definite */ ;
select * from system.ingresstest where val3 = 'R' /* definite */ ;
select val0 from system.ingresstest where val3 = 'R' /* definite */ ;
select avg(val0) from system.ingresstest /* definite */ ;
select stdev(val0) from system.ingresstest /* definite */ ;
select variance(val0) from system.ingresstest /* definite */ ;
select variance(val0), stdev(val0) from system.ingresstest /* definite */ ;
select * from system.ingresstest where val3 is null /* definite */ ;
select * from system.ingresstest where val3 is not null /* definite */ ;
select * from system.ingresstest where not val3 is null /* definite */ ;
select 1 from system.ingresstest /* definite */ ;
select 'a' from system.ingresstest /* definite */ ;
select * from system.ingresstest where val4 > date('1994-01-01') /* definite */ ;
select * from system.ingresstest where val0 = val2 /* definite */ ;
